routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\WorkController;
use App\Http\Controllers\MonthController;
use App\Http\Controllers\EmployeeDaysController;
/*  
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group([
//     'namespace'  => 'App\Http\Controllers\Admin',
//     'prefix'     => 'admin',
//     'middleware' => ['auth'],
// ], function () {
//     Route::resource('user', 'UserController');
//     Route::resource('role', 'RoleController');
//     Route::resource('permission', 'PermissionController');
// });

Route::get('login', [\App\Http\Controllers\AuthController::class, 'login'])->name('login');
Route::post('authenticate', [\App\Http\Controllers\AuthController::class, 'authenticate'])->name('authenticate');
Route::post('logout', [\App\Http\Controllers\AuthController::class, 'logout'])->name('logout');


Route::middleware('auth')->group(function () {
    Route::get('/', [\App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::group(['prefix' => 'users'], function () {
        Route::get('/list', [\App\Http\Controllers\EmployeesController::class, 'index'])->name('employees.list');
        Route::post('/add', [\App\Http\Controllers\EmployeesController::class, 'add'])->name('employees.add');
        Route::post('/store', [\App\Http\Controllers\EmployeesController::class, 'store'])->name('employees.store');
        Route::get('/edit/{id}', [\App\Http\Controllers\EmployeesController::class, 'edit'])->name('employees.edit');
        Route::put('/update/{id}', [\App\Http\Controllers\EmployeesController::class, 'update'])->name('employees.update');
        Route::post('/delete/{id}', [\App\Http\Controllers\EmployeesController::class, 'delete'])->name('employees.delete');
        Route::delete('/destroy/{id}', [\App\Http\Controllers\EmployeesController::class, 'destroy'])->name('employees.destroy');
        Route::get('/show/{id}', [\App\Http\Controllers\EmployeesController::class, 'show'])->name('employees.show');
        Route::get('/create', [\App\Http\Controllers\EmployeesController::class, 'create'])->name('employees.create');

//        Route::get('/index', [\App\Http\Controllers\RoleController::class, 'index'])->name('roles.index');

    });
  //  Route::resource('users', \App\Http\Controllers\EmployeesController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('works', WorkController::class);
    Route::resource('month', MonthController::class);
    Route::resource('days', EmployeeDaysController::class);
    Route::group(['prefix' => 'days'], function () {
        Route::get('/createday/{id}/{month_id}/{year}', [\App\Http\Controllers\EmployeeDaysController::class, 'createday'])->name('days.createday');
        Route::get('/list/{month_id}/{year}', [\App\Http\Controllers\EmployeeDaysController::class, 'list'])->name('days.list');
        Route::get('/select', [\App\Http\Controllers\EmployeeDaysController::class, 'select'])->name('days.select');
        Route::post('/store2', [\App\Http\Controllers\EmployeeDaysController::class, 'store2'])->name('days.store2');
    });
    Route::group(['prefix' => 'director-profile'], function () {
        Route::get('/list', [\App\Http\Controllers\DirectorProfileController::class, 'index'])->name('director.list');
        Route::get('/employees', [\App\Http\Controllers\DirectorProfileController::class, 'employees'])->name('director.employees');
        Route::get('/add/{month}/{year}', [\App\Http\Controllers\DirectorProfileController::class, 'add'])->name('director.add');
        Route::post('/store', [\App\Http\Controllers\DirectorProfileController::class, 'store'])->name('director.store');
        Route::post('/commit', [\App\Http\Controllers\DirectorProfileController::class, 'commit'])->name('director.commit');
        Route::get('/delete/{id}', [\App\Http\Controllers\DirectorProfileController::class, 'delete'])->name('director.delete');
        Route::get('/warn', [\App\Http\Controllers\DirectorProfileController::class, 'warn'])->name('director.warn');
        Route::get('/add2', [\App\Http\Controllers\DirectorProfileController::class, 'add2'])->name('director.add2');
        Route::post('/month_store', [\App\Http\Controllers\DirectorProfileController::class, 'month_store'])->name('director.month_store');

    });
    Route::group(['prefix' => 'commission-profile'], function () {
        Route::get('/list', [\App\Http\Controllers\KomissionController::class, 'index'])->name('commission.list');
        Route::get('/add/{id}', [\App\Http\Controllers\KomissionController::class, 'add'])->name('commission.add');
        Route::get('/edit/{id}/{month_id}/{year}', [\App\Http\Controllers\KomissionController::class, 'edit'])->name('commission.edit');
        Route::post('/store', [\App\Http\Controllers\KomissionController::class, 'store'])->name('commission.store');
        Route::post('/store2', [\App\Http\Controllers\KomissionController::class, 'store2'])->name('commission.store2');
        Route::post('/update/{id}', [\App\Http\Controllers\KomissionController::class, 'update'])->name('commission.update');
        Route::get('/get-file', [\App\Http\Controllers\KomissionController::class, 'getFile'])->name('commission.file');
        Route::post('/ball', [ \App\Http\Controllers\KomissionController::class, 'AddBall' ])->name('commission.ball');
        Route::get('/ball.edit/{id}', [ \App\Http\Controllers\KomissionController::class, 'BallEdit' ])->name('commission.ball.edit');
        Route::get('/calculate/{id}/{month_id}', [\App\Http\Controllers\KomissionController::class, 'calculate'])->name('commission.calculate');
        Route::post('/upload', [\App\Http\Controllers\KomissionController::class, 'upload'])->name('commission.upload');
        Route::get('/download/{id}', [\App\Http\Controllers\KomissionController::class, 'download'])->name('commission.download');
        Route::get('/section', [\App\Http\Controllers\KomissionController::class, 'section'])->name('commission.section');

        Route::get('/text', [\App\Http\Controllers\KomissionController::class, 'text'])->name('commission.text');
    });
    Route::group(['prefix' => 'employee-profile'], function () {
        Route::get('/list', [\App\Http\Controllers\EmployeeProfileController::class, 'index'])->name('profile.list');
        Route::get('/add', [\App\Http\Controllers\EmployeeProfileController::class, 'add'])->name('profile.add');
        Route::get('/create/{month}/{year}', [\App\Http\Controllers\EmployeeProfileController::class, 'create'])->name('profile.create');
        Route::post('/commit', [\App\Http\Controllers\EmployeeProfileController::class, 'commit'])->name('profile.commit');
        Route::post('/store', [\App\Http\Controllers\EmployeeProfileController::class, 'store'])->name('profile.store');
        Route::get('/add2', [\App\Http\Controllers\EmployeeProfileController::class, 'add2'])->name('profile.add2');
        Route::post('/month_store', [\App\Http\Controllers\EmployeeProfileController::class, 'month_store'])->name('profile.month_store');

        Route::post('/save', [\App\Http\Controllers\EmployeeProfileController::class, 'save'])->name('profile.save');
        Route::get('/delete/{id}', [\App\Http\Controllers\EmployeeProfileController::class, 'delete'])->name('profile.delete');
        Route::get('/create2', [\App\Http\Controllers\EmployeeProfileController::class, 'create2'])->name('profile.create2');
        Route::post('/warn', [\App\Http\Controllers\EmployeeProfileController::class, 'warn'])->name('profile.warn');
        Route::post('/save2', [\App\Http\Controllers\EmployeeProfileController::class, 'save2'])->name('profile.save2');
        Route::get('/upload', [ \App\Http\Controllers\EmployeeProfileController::class, 'upload' ])->name('profile.upload');
        Route::get('/download/{id}', [\App\Http\Controllers\EmployeeProfileController::class, 'download'])->name('profile.download');
        Route::post('/image.store', [ \App\Http\Controllers\EmployeeProfileController::class, 'ImageStore' ])->name('profile.image.store');
    });
    Route::group(['prefix' => 'bugalter'], function () {
        Route::get('/list', [\App\Http\Controllers\BugalterController::class, 'index'])->name('bugalter.list');
        Route::get('/add', [\App\Http\Controllers\BugalterController::class, 'add'])->name('bugalter.add');
        Route::get('/check', [\App\Http\Controllers\BugalterController::class, 'check'])->name('bugalter.check');
        Route::post('/store', [\App\Http\Controllers\BugalterController::class, 'store'])->name('bugalter.store');
        Route::get('/distribution/{id}', [\App\Http\Controllers\BugalterController::class, 'distribution'])->name('bugalter.distribution');
        Route::post('/update/{id}', [\App\Http\Controllers\BugalterController::class, 'update'])->name('bugalter.update');
        Route::get('/edit/{id}', [\App\Http\Controllers\BugalterController::class, 'edit'])->name('bugalter.edit');
        Route::get('/select', [\App\Http\Controllers\BugalterController::class, 'select'])->name('bugalter.select');
        Route::get('/export',[\App\Http\Controllers\BugalterController::class, 'get_summa'])->name('bugalter.export');
        Route::get('/calculate/{id}',[\App\Http\Controllers\BugalterController::class, 'calculate'])->name('bugalter.calculate');
    });
});

app/View/Components/layouts/main.php
<?php

namespace App\View\Components\layouts;

use Illuminate\View\Component;

class main extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.layouts.main');
    }
}

resources/views/layouts/blocks/footer.blade.php
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright ©  {{ @date('Y') }} yil</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Dastur <a href="https://agroinspeksiya.uz">&laquo;O'ZAGROINSPEKSIYA&raquo;</a> tomonidan ishlab chiqilgan </span>
    </div>
</footer><?php

resources/views/layouts/blocks/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <img style="width: 100px; margin: auto;" src="{{ url('/assets/images/logoNEW.png') }}" alt="logo">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="text-wrapper">
                    <p class="profile-name m-0">{{ auth()->user()->first_name. ' '.auth()->user()->last_name }}</p>
                </div>
            </a>
        </li>
        @if(auth()->user()->role_id == 1)
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#employees" aria-expanded="false"
                   aria-controls="ui-basic">
                    <i class="menu-icon typcn typcn-coffee"></i>
                    <span class="menu-title">Foydalanuvchilar</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="employees">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('employees.list')}}">Ro'yxatni ko'rish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('roles.index')}}">Foydalanuvchi rollari</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('works.index')}}">Foydalanuvchi ish joylari</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('month.index')}}">Ish kunlari</a>
                        </li>
                    </ul>
                </div>
            </li>
        @elseif(auth()->user()->role_id == 3)
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#profile" aria-expanded="false"
                   aria-controls="ui-basic">
                    <i class="menu-icon typcn typcn-coffee"></i>
                    <span class="menu-title">Baholash ko'rsatkichlari</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="profile">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('profile.list')}}">Holatni tekshirish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('profile.add2')}}">Ko'rsatkichlarni qo'shish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('profile.upload')}}">Baholarni to'ldirish</a>
                        </li>

                    </ul>
                </div>
            </li>
        @elseif(auth()->user()->role_id == 2)
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#kpi" aria-expanded="false" aria-controls="ui-basic">
                    <i class="menu-icon typcn typcn-coffee"></i>
                    <span class="menu-title">Baholash ko'rsatkichlari</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="kpi">
                    <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                            <a class="nav-link" href="{{route('director.list')}}">Holatni tekshirish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('director.add2')}}">Ko'rsatgichlar qo'shish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('director.employees')}}">Bo'lim xodimlari</a>
                        </li>

                    </ul>
                </div>
            </li>
        @elseif(auth()->user()->role_id == 6)
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#kpi" aria-expanded="false" aria-controls="ui-basic">
                    <i class="menu-icon typcn typcn-coffee"></i>
                    <span class="menu-title">Xodimlar natijalari</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="kpi">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('bugalter.list')}}">Taqsimot holatini ko'rish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('bugalter.add')}}">Summani kiritish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('bugalter.check')}}">Holatni tekshirish</a>
                        </li>
                    </ul>
                </div>
            </li>
        @elseif(auth()->user()->role_id == 4)
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#profile" aria-expanded="false"
                   aria-controls="ui-basic">
                    <i class="menu-icon typcn typcn-coffee"></i>
                    <span class="menu-title">Shaxsiy profil</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="profile">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('commission.list')}}">Xodimlar natijalari</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('days.select')}}">Xodimlar ish kunlari</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('commission.section')}}">Bo'limlar ro'yxati</a>
                        </li>
                    </ul>
                </div>
            </li>
        @elseif(auth()->user()->role_id == 7)
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#profile" aria-expanded="false"
                   aria-controls="ui-basic">
                    <i class="menu-icon typcn typcn-coffee"></i>
                    <span class="menu-title">Shaxsiy profil</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="profile">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('commission.section')}}">Bo'limlar ro'yxati</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('commission.list')}}">Xodimlar ro'yxati</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('bugalter.list')}}">Oylik hisobotlar</a>
                        </li>
                    </ul>
                </div>
            </li>
        @endif
    </ul>
</nav>
<style>
    .nav-link {
        white-space: normal !important;
    }
</style>

<script>

</script>

resources/views/layouts/blocks/top_navbar.blade.php
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <h2 style="font-size: 22px; color: white; margin: 0!important;">O'ZAGROINSPEKSIYA</h2>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center">
        <ul class="navbar-nav">
            <li class="nav-item font-weight-semibold">
                <i class="fa fa-bars" id="toggle-icon"></i>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            @auth
            <li class="nav-item">
                {{ auth()->user()->first_name. ' '.auth()->user()->last_name }}
            </li>
            <li class="nav-item d-none d-xl-inline-block">
                <form action="/logout" method="POST">
                    @csrf
                    <button type="submit" class="btn btn-primary"><i class="mdi mdi-logout"></i>Chiqish</button>
                </form>
            </li>
            @endauth
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>