routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\WorkController;
use App\Http\Controllers\MonthController;
use App\Http\Controllers\EmployeeDaysController;
/*  
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group([
//     'namespace'  => 'App\Http\Controllers\Admin',
//     'prefix'     => 'admin',
//     'middleware' => ['auth'],
// ], function () {
//     Route::resource('user', 'UserController');
//     Route::resource('role', 'RoleController');
//     Route::resource('permission', 'PermissionController');
// });

Route::get('login', [\App\Http\Controllers\AuthController::class, 'login'])->name('login');
Route::post('authenticate', [\App\Http\Controllers\AuthController::class, 'authenticate'])->name('authenticate');
Route::post('logout', [\App\Http\Controllers\AuthController::class, 'logout'])->name('logout');


Route::middleware('auth')->group(function () {
    Route::get('/', [\App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::group(['prefix' => 'users'], function () {
        Route::get('/list', [\App\Http\Controllers\EmployeesController::class, 'index'])->name('employees.list');
        Route::post('/add', [\App\Http\Controllers\EmployeesController::class, 'add'])->name('employees.add');
        Route::post('/store', [\App\Http\Controllers\EmployeesController::class, 'store'])->name('employees.store');
        Route::get('/edit/{id}', [\App\Http\Controllers\EmployeesController::class, 'edit'])->name('employees.edit');
        Route::put('/update/{id}', [\App\Http\Controllers\EmployeesController::class, 'update'])->name('employees.update');
        Route::post('/delete/{id}', [\App\Http\Controllers\EmployeesController::class, 'delete'])->name('employees.delete');
        Route::delete('/destroy/{id}', [\App\Http\Controllers\EmployeesController::class, 'destroy'])->name('employees.destroy');
        Route::get('/show/{id}', [\App\Http\Controllers\EmployeesController::class, 'show'])->name('employees.show');
        Route::get('/create', [\App\Http\Controllers\EmployeesController::class, 'create'])->name('employees.create');

//        Route::get('/index', [\App\Http\Controllers\RoleController::class, 'index'])->name('roles.index');

    });
  //  Route::resource('users', \App\Http\Controllers\EmployeesController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('works', WorkController::class);
    Route::resource('month', MonthController::class);
    Route::resource('days', EmployeeDaysController::class);
    Route::group(['prefix' => 'days'], function () {
        Route::get('/createday/{id}/{month_id}/{year}', [\App\Http\Controllers\EmployeeDaysController::class, 'createday'])->name('days.createday');
        Route::get('/list/{month_id}/{year}', [\App\Http\Controllers\EmployeeDaysController::class, 'list'])->name('days.list');
        Route::get('/select', [\App\Http\Controllers\EmployeeDaysController::class, 'select'])->name('days.select');
        Route::post('/store2', [\App\Http\Controllers\EmployeeDaysController::class, 'store2'])->name('days.store2');
    });
    Route::group(['prefix' => 'director-profile'], function () {
        Route::get('/list', [\App\Http\Controllers\DirectorProfileController::class, 'index'])->name('director.list');
        Route::get('/employees', [\App\Http\Controllers\DirectorProfileController::class, 'employees'])->name('director.employees');
        Route::get('/add/{month}/{year}', [\App\Http\Controllers\DirectorProfileController::class, 'add'])->name('director.add');
        Route::post('/store', [\App\Http\Controllers\DirectorProfileController::class, 'store'])->name('director.store');
        Route::post('/commit', [\App\Http\Controllers\DirectorProfileController::class, 'commit'])->name('director.commit');
        Route::get('/delete/{id}', [\App\Http\Controllers\DirectorProfileController::class, 'delete'])->name('director.delete');
        Route::get('/warn', [\App\Http\Controllers\DirectorProfileController::class, 'warn'])->name('director.warn');
        Route::get('/add2', [\App\Http\Controllers\DirectorProfileController::class, 'add2'])->name('director.add2');
        Route::post('/month_store', [\App\Http\Controllers\DirectorProfileController::class, 'month_store'])->name('director.month_store');

    });
    Route::group(['prefix' => 'commission-profile'], function () {
        Route::get('/list', [\App\Http\Controllers\KomissionController::class, 'index'])->name('commission.list');
        Route::get('/add/{id}', [\App\Http\Controllers\KomissionController::class, 'add'])->name('commission.add');
        Route::get('/edit/{id}/{month_id}/{year}', [\App\Http\Controllers\KomissionController::class, 'edit'])->name('commission.edit');
        Route::post('/store', [\App\Http\Controllers\KomissionController::class, 'store'])->name('commission.store');
        Route::post('/store2', [\App\Http\Controllers\KomissionController::class, 'store2'])->name('commission.store2');
        Route::post('/update/{id}', [\App\Http\Controllers\KomissionController::class, 'update'])->name('commission.update');
        Route::get('/get-file', [\App\Http\Controllers\KomissionController::class, 'getFile'])->name('commission.file');
        Route::post('/ball', [ \App\Http\Controllers\KomissionController::class, 'AddBall' ])->name('commission.ball');
        Route::get('/ball.edit/{id}', [ \App\Http\Controllers\KomissionController::class, 'BallEdit' ])->name('commission.ball.edit');
        Route::get('/calculate/{id}/{month_id}', [\App\Http\Controllers\KomissionController::class, 'calculate'])->name('commission.calculate');
        Route::post('/upload', [\App\Http\Controllers\KomissionController::class, 'upload'])->name('commission.upload');
        Route::get('/download/{id}', [\App\Http\Controllers\KomissionController::class, 'download'])->name('commission.download');
        Route::get('/section', [\App\Http\Controllers\KomissionController::class, 'section'])->name('commission.section');

        Route::get('/text', [\App\Http\Controllers\KomissionController::class, 'text'])->name('commission.text');
    });
    Route::group(['prefix' => 'employee-profile'], function () {
        Route::get('/list', [\App\Http\Controllers\EmployeeProfileController::class, 'index'])->name('profile.list');
        Route::get('/add', [\App\Http\Controllers\EmployeeProfileController::class, 'add'])->name('profile.add');
        Route::get('/create/{month}/{year}', [\App\Http\Controllers\EmployeeProfileController::class, 'create'])->name('profile.create');
        Route::post('/commit', [\App\Http\Controllers\EmployeeProfileController::class, 'commit'])->name('profile.commit');
        Route::post('/store', [\App\Http\Controllers\EmployeeProfileController::class, 'store'])->name('profile.store');
        Route::get('/add2', [\App\Http\Controllers\EmployeeProfileController::class, 'add2'])->name('profile.add2');
        Route::post('/month_store', [\App\Http\Controllers\EmployeeProfileController::class, 'month_store'])->name('profile.month_store');

        Route::post('/save', [\App\Http\Controllers\EmployeeProfileController::class, 'save'])->name('profile.save');
        Route::get('/delete/{id}', [\App\Http\Controllers\EmployeeProfileController::class, 'delete'])->name('profile.delete');
        Route::get('/create2', [\App\Http\Controllers\EmployeeProfileController::class, 'create2'])->name('profile.create2');
        Route::post('/warn', [\App\Http\Controllers\EmployeeProfileController::class, 'warn'])->name('profile.warn');
        Route::post('/save2', [\App\Http\Controllers\EmployeeProfileController::class, 'save2'])->name('profile.save2');
        Route::get('/upload', [ \App\Http\Controllers\EmployeeProfileController::class, 'upload' ])->name('profile.upload');
        Route::get('/download/{id}', [\App\Http\Controllers\EmployeeProfileController::class, 'download'])->name('profile.download');
        Route::post('/image.store', [ \App\Http\Controllers\EmployeeProfileController::class, 'ImageStore' ])->name('profile.image.store');
    });
    Route::group(['prefix' => 'bugalter'], function () {
        Route::get('/list', [\App\Http\Controllers\BugalterController::class, 'index'])->name('bugalter.list');
        Route::get('/add', [\App\Http\Controllers\BugalterController::class, 'add'])->name('bugalter.add');
        Route::get('/check', [\App\Http\Controllers\BugalterController::class, 'check'])->name('bugalter.check');
        Route::post('/store', [\App\Http\Controllers\BugalterController::class, 'store'])->name('bugalter.store');
        Route::get('/distribution/{id}', [\App\Http\Controllers\BugalterController::class, 'distribution'])->name('bugalter.distribution');
        Route::post('/update/{id}', [\App\Http\Controllers\BugalterController::class, 'update'])->name('bugalter.update');
        Route::get('/edit/{id}', [\App\Http\Controllers\BugalterController::class, 'edit'])->name('bugalter.edit');
        Route::get('/select', [\App\Http\Controllers\BugalterController::class, 'select'])->name('bugalter.select');
        Route::get('/export',[\App\Http\Controllers\BugalterController::class, 'get_summa'])->name('bugalter.export');
        Route::get('/calculate/{id}',[\App\Http\Controllers\BugalterController::class, 'calculate'])->name('bugalter.calculate');
    });
});

app/Http/Controllers/WorkController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\WorkZone;

class WorkController extends Controller
{
      /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $works = WorkZone::orderBy('id','asc')->paginate(10);
        return view('works.index', compact('works'));
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        return view('works.create');
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        
        WorkZone::create($request->post());

        return redirect()->route('works.index')->with('success','Ish joyi muvaffaqatli yaratildi.');
    }

    /**
    * Display the specified resource.
    *
    * @param  \App\company  $company
    * @return \Illuminate\Http\Response
    */
    public function show(WorkZone $work)
    {
        return view('works.show',compact('work'));
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Company  $company
    * @return \Illuminate\Http\Response
    */
    public function edit(WorkZone $work)
    {
        return view('works.edit',compact('work'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\company  $company
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, WorkZone $work)
    {
        $request->validate([
            'name' => 'required',
        ]);
        
        $work->fill($request->post())->save();

        return redirect()->route('works.index')->with('success','Ma\'lumotlar muvaffaqiyatli o\'zgartirildi');
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Company  $company
    * @return \Illuminate\Http\Response
    */
    public function destroy(WorkZone $work)
    {
        $work->delete();
        return redirect()->route('works.index')->with('success','Ma\'lumotlar muvaffaqiyatli o\'chirildi');
    }
}

resources/views/works/create.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
<div class="container mt-2">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left mb-2">
                    <h2>Ish joyi qo'shish</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('works.index') }}"> Ortga</a>
                </div>
            </div>
        </div>
        @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
        @endif
        <form action="{{ route('works.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nomi:</strong>
                        <input type="text" name="name" class="form-control" placeholder="Nomi">
                        @error('name')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <button type="submit" class="btn btn-primary ml-3">Saqlash</button>
            </div>
        </form>
    </div>
</div>
    @endsection

resources/views/works/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
<div class="container mt-2">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Tahrirlash</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('works.index') }}" enctype="multipart/form-data">
                        Orqaga</a>
                </div>
            </div>
        </div>
        @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
        @endif
        <form action="{{ route('works.update',$work->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Ish joyi nomi:</strong>
                        <input type="text" name="name" value="{{ $work->name }}" class="form-control"
                            placeholder="Nomi">
                        @error('name')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <button type="submit" class="btn btn-primary ml-3">Saqlash</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/works/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
        <div class="row ">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body" style="background-color:white">
                        <!-- <div class="col-lg-12 grid-margin stretch-card">
                         <div class="card"> -->
                        <!-- <div class="card-body"> -->
                        <h2>Foydalanuvchilarning ish joylari</h2>

                        <div class="pull-right mb-2">
                            <a class="btn btn-success" href="{{ route('works.create') }}">  Yaratish</a>
                        </div>
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        <table class="table table-bordered table-responsive">
                            <thead>
                            <tr>
                                <th>Tartib raqam</th>
                                <th>Nomi</th>
                                <th>Yaratilgan vaqti</th>
                                <th>O'zgartirilgan vaqti</th>
                                <th width="280px">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($works as $work)
                                <tr>
                                    <td>{{ $work->id }}</td>
                                    <td>{{ $work->name }}</td>
                                    <td>{{ $work->created_at }}</td>
                                    <td>{{ $work->updated_at }}</td>
                                    <td>
                                        <form action="{{ route('works.destroy',$work->id) }}" method="Post">
                                            <a class="btn btn-primary" href="{{ route('works.edit',$work->id) }}">Tahrirlash</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">O'chirish</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {!! $works->links() !!}
                    </div>
                </div>

    </div>
</div>
</div>
@endsection